
services:
  app:
    build: .
    restart: on-failure
    ports:
      - '3000:3000'
    depends_on:
      - mysql
    env_file:
      - .env
    command: sh -c "bunx prisma db push  && bun run start"
    environment:
      - DATABASE_URL=mysql://user:password@mysql:3306/mydb
    

  mysql:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: mydb
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    volumes:
      - mysql-data:/var/lib/mysql
    ports:
      - '3306:3306'

volumes:
  mysql-data:
